# Generated by Django 4.1 on 2024-05-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_parent1_parent2_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent1_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='testapp.parent1'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent2_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.parent2'),
        ),
    ]
