# Generated by Django 4.1 on 2024-05-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_child_parent1_ptr_alter_child_parent2_ptr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent1',
            old_name='f1',
            new_name='f3',
        ),
        migrations.RenameField(
            model_name='parent1',
            old_name='f2',
            new_name='f4',
        ),
        migrations.RenameField(
            model_name='parent2',
            old_name='f3',
            new_name='f1',
        ),
        migrations.RenameField(
            model_name='parent2',
            old_name='f4',
            new_name='f2',
        ),
        migrations.AlterField(
            model_name='child',
            name='parent1_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.parent1'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent2_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='testapp.parent2'),
        ),
    ]
